swagger: '2.0'
info:
  version: '1.0'
  title: Election Collection
  description: 'TODO: Add Description'
  contact: {}
host: localhost:4200
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /district/create:
    post:
      description: 'TODO: Add Description'
      summary: district-create
      tags:
      - Misc
      operationId: DistrictCreatePost
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: jwt
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/DistrictCreaterequest'
      responses:
        200:
          description: ''
  /districts:
    get:
      description: 'TODO: Add Description'
      summary: get-districts
      tags:
      - Misc
      operationId: DistrictsGet
      produces:
      - application/json
      parameters:
      - name: jwt
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
  /user/create:
    post:
      description: 'TODO: Add Description'
      summary: user-create
      tags:
      - Misc
      operationId: UserCreatePost
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: jwt
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/UserCreaterequest'
      responses:
        200:
          description: ''
  /authenticate:
    post:
      description: 'TODO: Add Description'
      summary: authenticate
      tags:
      - Misc
      operationId: AuthenticatePost
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/AuthenticateRequest'
      responses:
        200:
          description: ''
  /party/create:
    post:
      description: 'TODO: Add Description'
      summary: party-create
      tags:
      - Misc
      operationId: PartyCreatePost
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: jwt
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/PartyCreaterequest'
      responses:
        200:
          description: ''
  /parties:
    get:
      description: 'TODO: Add Description'
      summary: get-parties
      tags:
      - Misc
      operationId: PartiesGet
      produces:
      - application/json
      parameters:
      - name: jwt
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
  /candidate/create:
    post:
      description: 'TODO: Add Description'
      summary: candidate-create
      tags:
      - Misc
      operationId: CandidateCreatePost
      produces:
      - application/json
      parameters:
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: jwt
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/CandidateCreaterequest'
      responses:
        200:
          description: ''
  /candidates:
    get:
      description: 'TODO: Add Description'
      summary: get-candidates
      tags:
      - Misc
      operationId: CandidatesGet
      produces:
      - application/json
      parameters:
      - name: jwt
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
  /election/create:
    post:
      description: 'TODO: Add Description'
      summary: election-create
      tags:
      - Misc
      operationId: ElectionCreatePost
      produces:
      - application/json
      parameters:
      - name: jwt
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/ElectionCreaterequest'
      responses:
        200:
          description: ''
  /candidates/electionid/4:
    get:
      description: 'TODO: Add Description'
      summary: get-candidates-for-election
      tags:
      - Misc
      operationId: CandidatesElectionid4Get
      produces:
      - application/json
      parameters:
      - name: jwt
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
  /election/vote:
    post:
      description: 'TODO: Add Description'
      summary: election-vote
      tags:
      - Misc
      operationId: ElectionVotePost
      produces:
      - application/json
      parameters:
      - name: jwt
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      - name: Body
        in: body
        required: true
        description: ''
        schema:
          $ref: '#/definitions/ElectionVoterequest'
      responses:
        200:
          description: ''
  /ballot:
    get:
      description: 'TODO: Add Description'
      summary: get-ballot
      tags:
      - Misc
      operationId: BallotGet
      produces:
      - application/json
      parameters:
      - name: jwt
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
  /election/result/electionid/4:
    get:
      description: 'TODO: Add Description'
      summary: get-election-result
      tags:
      - Misc
      operationId: ElectionResultElectionid4Get
      produces:
      - application/json
      parameters:
      - name: jwt
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
definitions:
  DistrictCreaterequest:
    title: district-createRequest
    example:
      name: Washington State
      parentDistrictId: 1
    type: object
    properties:
      name:
        description: ''
        type: string
      parentDistrictId:
        description: ''
        type: integer
        format: int32
    required:
    - name
    - parentDistrictId
  UserCreaterequest:
    title: user-createRequest
    example:
      username: Daisy
      password: password
      email: Jim@mike.com
      districtId: 3
    type: object
    properties:
      username:
        description: ''
        type: string
      password:
        description: ''
        type: string
      email:
        description: ''
        type: string
      districtId:
        description: ''
        type: integer
        format: int32
    required:
    - username
    - password
    - email
    - districtId
  AuthenticateRequest:
    title: authenticateRequest
    example:
      username: Daisy
      password: password
    type: object
    properties:
      username:
        description: ''
        type: string
      password:
        description: ''
        type: string
    required:
    - username
    - password
  PartyCreaterequest:
    title: party-createRequest
    example:
      name: Democrat
    type: object
    properties:
      name:
        description: ''
        type: string
    required:
    - name
  CandidateCreaterequest:
    title: candidate-createRequest
    example:
      name: Hillary Clinton
      party: 2
    type: object
    properties:
      name:
        description: ''
        type: string
      party:
        description: ''
        type: integer
        format: int32
    required:
    - name
    - party
  ElectionCreaterequest:
    title: election-createRequest
    example:
      name: Presidental Election
      end: 2018-11-25 10:54:06
      start: 2018-10-25 10:54:06
      district: 1
      candidates:
      - candidateId: 1
      - candidateId: 2
    type: object
    properties:
      name:
        description: ''
        type: string
      end:
        description: ''
        type: string
      start:
        description: ''
        type: string
      district:
        description: ''
        type: integer
        format: int32
      candidates:
        description: ''
        type: array
        items:
          $ref: '#/definitions/Candidate'
    required:
    - name
    - end
    - start
    - district
    - candidates
  Candidate:
    title: Candidate
    type: object
    properties:
      candidateId:
        description: ''
        type: integer
        format: int32
    required:
    - candidateId
  ElectionVoterequest:
    title: election-voteRequest
    example:
      candidateId: 6
      electionId: 4
    type: object
    properties:
      candidateId:
        description: ''
        type: integer
        format: int32
      electionId:
        description: ''
        type: integer
        format: int32
    required:
    - candidateId
    - electionId
tags:
- name: Misc
  description: ''
